server:
  port: 8088

spring:
  application:
    name: k8s-example2-mysql
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/user
    username: root
    password: root
  flyway:
    enabled: true
    schemas: user

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect