version: "3.8"

services:
  mysqldb-microservice:
    container_name: mysqldb-microservice
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trip
    networks:
      springboot-trip-net:

  trip-service:
    container_name: trip-service
    build: ./trip-service
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb-microservice
    networks:
      springboot-trip-net:

networks:
  springboot-trip-net:

volumes:
  db: