server:
  port: 8089
spring:
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  docker:
    compose:
      enabled: true
      file: kafka-producer-wikimedia/docker-compose.yml